/**
 * Action type to request the named reducer to update it latestState reference
 */
const _UPDATE_STATE_ACTION_TYPE_DONT_USE_ = 'namedReducer/updateState'

/**
 * Creates a store enhancer that passes the latest state object to named reducers for every state change
 *
 * @param {...Function} reducers the reducers to get the state changed action
 * @returns {Function} the store enhancer
 */
export function namedReducerEnhancer(...reducers) {
	return createStore => (...args) => {
		const store = createStore(...args)

		//listener to subscribe to the store
		function listener() {
			const state = store.getState()
			//inform all named reducers of the state change
			for (var i = 0, len = reducers.length; i < len; i++) {
				reducers[i](state, { type: _UPDATE_STATE_ACTION_TYPE_DONT_USE_ })
			}
		}

		store.subscribe(listener)

		return {
			...store
		}
	}
}

/**
 * Creates a named reducer to access redux state from  anywhere in your code.
 * Basically a reducer with a reference to the latest state object and autogenerated-selectors for each property from the reducers initial state.
 * Allows to retrieve the a given state by calling getState(namedReducer.stateName).
 *
 * @param {Object} options an object of the form { moduleName: <moduleName>, reducer: <reducer>, externalState: <optional> }
 * @returns {Function} the named reducer
 */
export function createNamedReducer(options) {
	const namedReducer = function(state, action) {
		if (action.type === _UPDATE_STATE_ACTION_TYPE_DONT_USE_) {
			//update the latestState reference
			namedReducer.latestState = state
			return state
		} else {
			//call the normal reducer
			return options.reducer(state, action)
		}
	}

	//reference to the latest state
	namedReducer.latestState = null

	//module name
	namedReducer.moduleName = options.moduleName

	//create a selector for each first level property in the initial state
	Object.keys(options.reducer(undefined, { type: undefined })).forEach(e => {
		namedReducer[e] = function(state) {
			return state ? state[namedReducer.moduleName][e] : namedReducer.latestState[e]
		}
	})

	//create a default value selector for each external state
	if (options.externalState) {
		Object.keys(options.externalState).forEach(e => {
			namedReducer[e] = function() {
				return options.externalState[e] //return the default value
			}
		})
	}

	return namedReducer
}

/**
 * Calls the selector from a named reducer
 *
 * @param {Function} selector the selector to call
 * @returns {Any} the value returned by the selector
 */
export function getState(selector) {
	return selector()
}
